[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Response.missing = true}

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"
    Cache-Control = "no-cache"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type" 